### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by woodepic** [woodepic/soundSentry#3]
Todo:

- [x] Get LCD Working
- [x] Get mics to interface with Arduino
    - [ ] Investigage better serial plotting? https://arduino.stackexchange.com/questions/1180/serial-data-plotting-programs
- [ ] Write code to accurately measure dB from one mic
    -  Turns out, amplitude of wave does not correlate to signal energy. Must work with FFT to calculate power.
- [ ] Measure dB from 3 mics, and build voting algorithm (Most similar two values are averaged)
- [ ] Use multiplexers to measure db from 6 mics, build algorithm that can identify where a sound is coming from
- [ ] Set up dual core functionality, with db calculation on one core, wifi dashboard on the other core
    - [ ] Use freeRTOS to manage tasks?
- [ ] Build wifi dashboard
- [ ] add OTA flashing functionality
- [ ] Design PCB & outdoor enclosure
